# Generated by Django 5.2 on 2025-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0005_add_phone_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
