# Generated by Django 5.2 on 2025-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0008_alter_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
