# Generated by Django 5.2 on 2025-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0010_documnets_model_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео'), ('document', 'Документи'), ('audio', 'Аудіо'), ('other', 'Інше')], default='other', max_length=50),
        ),
    ]
