# Generated by Django 5.2 on 2025-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0011_docs_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Documents'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
