# Generated by Django 5.2 on 2025-04-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0013_alter_tag_slug'),
        ('pers_assist_app', '0013_uploadedfile_cloudinary_public_id_and_more'),
    ]

    operations = [
    ]
