# Generated by Django 5.2 on 2025-04-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0014_merge_20250419_1105'),
        ('pers_assist_app', '0015_alter_uploadedfile_uploaded_at'),
    ]

    operations = [
    ]
