# Generated by Django 5.2 on 2025-04-19 20:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0017_remove_uploadedfile_file_url_contact_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='cloudinary_public_id',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
