# Generated by Django 5.2 on 2025-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0019_alter_tag_slug_alter_tag_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
