# Generated by Django 5.2 on 2025-04-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pers_assist_app', '0020_alter_contact_phone_contact_unique_owner_phone'),
        ('pers_assist_app', '0020_uploadedfile_cloudinary_public_id'),
    ]

    operations = [
    ]
